### ISSUE TITLE
Cata Classic Support

### ISSUE THREAD

**Issue by Walayimuna** [ynazar1/Arh#12]
Any plans to make it compatible with cataclysm classic?

**Comment by ynazar1** [comment]
Since classic uses same API as retail it may just 'work'.... but I don't play classic so i'm unlikely to be able to do any real testing. 

I'm happy to collaborate to get it working, but my skills in wow addons is at a level of 'occasional bugfix'. I'm not particularly confident to maintaining two distinct sets of code between editions if there are significant differences.

**Comment by Walayimuna** [comment]
I can help in any way I know, maybe beta-test or something, when archaeology becomes available on PTR

**Comment by ynazar1** [comment]
We could try it out once Cataclysm reaches open beta or release. But there's been number of relevant API changes in the intervening years that would specifically affect Arh. Super ironically, the OLDER versions on curse may just work in Cata since they would use old APIs. 

[This article deals with some addon changes between retail and Classic](https://wowpedia.fandom.com/wiki/Porting_addons_to_Classic) and I can tell you that most of these changes affect Arh.

The original code is basically been hacked at by many people and while some things are simply commented out, there are other functions that I know were completely replaced over the years so they'll be hard to recover. You may see some examples of [changes that have been done here](https://github.com/ynazar1/Arh/blob/354cbf9b95c18824ce7b8a81b18557abf326e538/Arh.lua#L1143) and these types of changes are specifically outlined in the article about porting. 
[This one for example is above my skill](https://github.com/ynazar1/Arh/blob/354cbf9b95c18824ce7b8a81b18557abf326e538/Arh.lua#L1192) level to unravel if it needs to be fixed or redone.

**Comment by TamerLee** [comment]
Can confirm the latest version works on the Cataclysm beta. The two features not working at the moment are the node database, and being able to record new nodes.

**Comment by ynazar1** [comment]
Awesome. I don't have beta so I may need to wait till it opens up. The two things you mention hard-depend on GatherMate2 as It simply adds nodes to GatherMate's database.

**Comment by Walayimuna** [comment]
I'm offering to beta test if needed, I have access to the beta

**Comment by vtosh** [comment]
Can also confirm this appears to be working absolutly great on cata beta. At least in terms of keybinding dig/undo/red/yellow/green. Getting mounted automatically when using red/yellow markers (using the mount favorite no less!). Undo works correctly as well through multiple undo steps

As mentioned, node stuff isn't working. I assume thats because the "view" is a clone of the minimap in some form (like how farmhud works) which is why thats all gathermates realm? Unfortunatly we don't have a cata version of that yet. It was never officially backported to classic so we have gathermate2 classic instead, which only supports up to wotlk atm, and the retail version isn't compatible

**Comment by vtosh** [comment]
I managed to hack together a working version of gathermate2. I can now see nodes appear, however innitially the nodes didn't rotate with the camera. Toggling rotate minimap manually, then reloading the UI allowed the nodes to rotate with the camera. I'm assuming however this is just a part of gathermate2 that i didn't manage to correctly hack together, and will be fixed when an official cata version is released

**Comment by ynazar1** [comment]
@vtosh : I betcha it's related to #5 

Check what the [variable name on these lines here ](https://github.com/ynazar1/Arh/commit/a0837d92cc886114ab7341d9c048933974e0d749)
Vs What is it around line 27 of Gathermate2: Display.lua file (look for rotation). 

They must match

**Comment by vtosh** [comment]
Haha, I even had a diff of retail and classic Display.lua from gathermate2 open and I must have missed that cvar rename.

But that all but confirms, no changes appear to be required to support cata classic. The only thing that might be usful is adding an additional cata toc file, so it can be used without loading out of date addons (but given everyone in classic probably has that enabled not a problem). Other than that thanks for maintaining it!

**Comment by Walayimuna** [comment]
So I can just get this addon as is and use it on cata?

**Comment by ynazar1** [comment]
@Walayimuna  yes. Current version works fine. I was able to verify it as I got Cata beta access.
 
It works as is, but without gathermate2's archaeology tracking there are no nodes that show up on the HUD. Hopefully they'll put it back in once live. 

Two known bugs: 
1. gathermate2 dependency
Intentional: ~2. Druid shifts into travel form instead of flight form because they are different things in Cata. I may not bother to fix it.~

**Comment by Walayimuna** [comment]
And I can't use gathermate2 WotLK version, right ? For what I read here someone had to modify it's code, where can I find a compatible gathermate2 with beta?

**Comment by ynazar1** [comment]
That is correct. The WotLK Gathermate2 doesn't have archaeology profession tracking. 

You may be able to hack it in like @vtosh did or hack retail version to work with cata or wait for live. Since beta things don't really matter, I'd wait for live. I guess i'll be able to make sure that Arh works with whatever live gathermate2 version decides to do.

**Comment by Walayimuna** [comment]
It would be awesome to have a working version on the 30th, when prepatch goes live

**Comment by ynazar1** [comment]
You should poke at Gathermate2 Classic to put arcaeology back for node support. I really-really do not feel like hacking around another Gathermate fork (similar to the DF treasures one i did last year when they refused to track random treasure chests in DF)

**Comment by BjarkeM** [comment]
[AddOns.zip](https://github.com/ynazar1/Arh/files/15177732/AddOns.zip)
I've hacked together a fix for the gathermate2/gathermate2data addons to work with archaeology.

Most zones are mapped from the retail archaeology data to classic zones using IDs from this page: https://wowpedia.fandom.com/wiki/UiMapID

It's not 100% working (some zones are mapped incorrectly, but most of them are correct), but it's a start for anyone that wants the gathermate 2 nodes on this addon in classic.
To test the functionality:
Do this ingame EVERY TIME you reload/login and want to farm archaeology:
/gathermate
go to import
tick archaeology
click import GatherMate2Data

use Arh and the archaeology nodes will show up.

I didn't bother saving the points permanently, as it's not a complete fix - someone that cares enough can make a proper fix for gathermate2 classic :)

**Comment by Straken33** [comment]
Edit: issue seems to be with my second wow account, as its working fine on the first one...

**Comment by BjarkeM** [comment]
works fine on cata prepatch for me :)

**Comment by Walayimuna** [comment]
> I managed to hack together a working version of gathermate2. I can now see nodes appear, however innitially the nodes didn't rotate with the camera. Toggling rotate minimap manually, then reloading the UI allowed the nodes to rotate with the camera. I'm assuming however this is just a part of gathermate2 that i didn't manage to correctly hack together, and will be fixed when an official cata version is released

Can you please share your version of gathermate2, until there is official support for archaeology on the official gathermate2?

**Comment by ynazar1** [comment]
The current Arh release works in Cata beta!!!

This Gathermate2 (zip below) should probably do till the official version comes out. This is based on latest classic. I didn't test *all* functionality but it's fairly sure to work in Cata. Likely not in Classic or SoD.

@vtosh found the bug why it doesn't rotate in classic. You can see it here. https://github.com/Nevcairiel/GatherMate2/issues/25
My zipped copy includes the fix.

I was able to import Archaeology data successfully from GM2_Data addon in the @BjarkeM 's folder and it retains between restarts.

[GatherMate2.zip](https://github.com/ynazar1/Arh/files/15182878/GatherMate2.zip)

**Comment by ynazar1** [comment]
If anyone finds any new issues in latest release, please post here. Otherwise calling this complete

**Comment by Litvan** [comment]
> If anyone finds any new issues in latest release, please post here. Otherwise calling this complete

the 2.0.6-126 from 13 hrs ago?

*edit*
Seems to be working fine, with the above version of gathermate2 I even have the nice lil marker for where I dug up one
![image](https://github.com/ynazar1/Arh/assets/15156240/a9c1a16a-4a77-456b-95b0-9c810289da34)

**Comment by Quinty31519** [comment]
Thanks all for the help so far. I'm currently having the issue where there's a missing dependency "Blizzard_BattlefieldMinimap".

Without the dependency at all, Archaeology Helper doesn't work or respond to /arh at all. I then did some online searching for info about the above named minimap and found this page https://github.com/satan666/WOW-UI-SOURCE/tree/master/AddOns.

I didn't know how to properly take files from here so my fix was to copy the Blizzard_BattlefieldMinimap lua, toc, xml, and localization files individually, made a folder named Blizzard_BattlefieldMinimap, threw the 4 into it, and put the folder in my AddOns folder.

At this point, I was able to enter game and when I type /arh I get the menu of help/config options to show in chat, but typing /arh along with any of the options (t, toggle, h, hud, config, minimap...) does nothing at all.

I also only have the Archaeology Helper buttons but no superimposed map.

Lastly, I am currently using SexyMap for a minimap, but nothing else. Am going to disable that to see what happens next.

**Comment by ynazar1** [comment]
@Quinty31519  Arh doesn't 'normally' toggle unless you're on top of a digsite (see options about visibility). You can make it display by unchecking 'toggle with digsite' in options. I have no clue what superimposed map you mean. 

For what it's worth battlefield minimap support has always been a bit wonky, i recommend to not use it if you can.... Here's my addons folder for Cata beta... There's absolutely no point to even bother with it in classic at the moment. 

![image](https://github.com/ynazar1/Arh/assets/43916837/fe9f00e9-f91d-4b4e-b028-049d87fbb624)

**Comment by Quinty31519** [comment]
Edited original comment as I was referring to an older copy/release. Thanks @ynazar1 for clarifying! The post below/following this works in Cata Classic.

**Comment by ynazar1** [comment]
@Quinty31519  Lol! You're on wrong addon! 
![image](https://github.com/ynazar1/Arh/assets/43916837/7055ca50-12e5-401b-9b34-327e618daaf5) You've got unfortunately ancient version that still floating around addon sites. Because it's all rights reserved I cannot upload mine there. :( 

Grab the latest package from [releases ](https://github.com/ynazar1/Arh/releases) and delete the one you have. Also grab gathermate2 from this [post](https://github.com/ynazar1/Arh/issues/12#issuecomment-2089427000) for rotating nodes.

**Comment by Quinty31519** [comment]
Huge! I did have an old version, and it works now! <3

**Comment by ynazar1** [comment]
Update! 

Official Classic Gathermate2 have put Archaeology back with the latest release. We're good to go for Cata Launch as far as I can tell.
