### ISSUE TITLE
Issue with minimap

### ISSUE THREAD

**Issue by Matth4** [ynazar1/Arh#5]
I'm not sure if it's indented or not, but the overlay minimap don't rotate at all, which is realy disturbing as it feel like the cursor is sliding and not moving in the same direction you are.

**Comment by ynazar1** [comment]
Could you be more specific on how to reproduce it. What do you mean 'overlay minimap' not rotating? On the overlay HUD (which is the main screen where the color arches are placed) the arrow always points up because the addon assumes the camera is behind character and the character is looking 'forward'... but everything else in the HUD rotates.

**Comment by Matth4** [comment]
I made a short record it would be easier to picture it like that ;)

https://gyazo.com/18f3b8e15b56117cb67aa63753d7a078

**Comment by ynazar1** [comment]
Thank you!!!! This is intentional though a little disorienting.

The archeology nodes and your character position are actually on a flat coordinate plane... Imagine it as if looking top down onto a map, or gathering flowers on a lawn. So your character moves around while the archeology nodes remain in their predetermined positions. In other words, the world doesn't rotate, your character and camera do. The little circles on the screen are as if you're looking from the very top downwards with your character's position being represented by the arrow. 

The little arrow itself is a static texture. I could recommend to turn off the arrow and turn on the success circle in the options to make it a little less obvious that the little arrow doesn't rotate.

**Comment by Matth4** [comment]
I see, thanks for your answer :) It's indeed easier to pictures the whole scenary with the success circle turned on and the arrow off !
I was confused as in the youtube video I saw everything was rotating around so I though it was an issue with my settings or something :) ( https://gyazo.com/b0095165efeb7e7482bb07f9e6d8f7d1 )

Anyway, thanks again, and thanks for your work on keeping this addon alive ;)

**Comment by ynazar1** [comment]
Oh yeah, I recalled what it is! 

The whole HUD overlay with the nodes with rotate if you have "Rotate Minimap" option enabled. I personally really dislike rotating minimap so I never have that enabled. Doesn't change the functionality, but I guess with the arrow it's a little simpler to rotate minimap (and HUD) and with circle to have them static.

**Comment by ynazar1** [comment]
Apparently variable name changed in [dc9543580d03986098d3bf337748d34f1c3e44ea](https://github.com/Nevcairiel/GatherMate2/blob/dc9543580d03986098d3bf337748d34f1c3e44ea/Display.lua)
Breaking that functionality... Well fixed!
